spring:
# JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: update
      use-new-id-generator-mappings: true
  datasource:
    url: jdbc:mysql://localhost/imovies?characterEncoding=UTF-8
    username: root
    password: admin@power.oj
    driver-class-name: com.mysql.jdbc.Driver

logging:
  file: imovie-crawler.log
  level:
    org.power.oj: DEBUG
    org.springframework:
      security: DEBUG

url:
  rs05: http://www.rs05.com/movie/?p=
  btpan: http://www.btpan.com
  xyw: http://www.xunyingwang.com
  fix: http://www.fixsub.com/%E6%88%91%E4%BB%AC%E7%9A%84%E4%BD%9C%E5%93%81?set=
  douban: https://movie.douban.com
  imdb: http://www.imdb.com/search/title?count=100&title_type=feature,tv_series&view=simple&page=
  btt:
    site: http://btbtt.pw/
    page: http://btbtt.pw/forum-index-fid-%d-page-%d.htm
    thread: http://btbtt.pw/thread-index-fid-%d-tid-%d.htm
  rarbt:
    site: http://www.rarbt.com
    page: http://www.rarbt.com/index.php/index/index/p/%d.html
  bttt:
    site: http://www.bttiantang.org
    page: http://www.bttiantang.org/index-%d.html
  btapple:
    site: http://www.btapple.com
    page: http://www.btapple.com/%s/%d-0-0-0-0-%d.html
  btdy:
    site: http://www.btbtdy.com
    page: http://www.btbtdy.com/screen/0-----time-%d.html
  zmz:
    site: http://www.zimuzu.tv
    page: http://www.zimuzu.tv/fresourcelist?channel=tv&page=
file:
  download: /tmp/bt/

---
spring:
  profiles: dev
logging:
  level:
    org.springframework:
     web: DEBUG

---
spring:
  profiles: test
# JPA
  jpa:
    show-sql: true
    database: H2
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: create-drop
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
logging:
  level:
    org.springframework:
     web: DEBUG
