spring:
# JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: update
      use-new-id-generator-mappings: true
  datasource:
    url: jdbc:mysql://localhost/imovies?characterEncoding=UTF-8
    username: root
    password: admin@power.oj
    driver-class-name: com.mysql.jdbc.Driver

logging:
  file: imovie-crawler.log
  level:
    org.power.oj: DEBUG
    org.springframework:
      security: DEBUG

url:
  rs05: http://www.rs05.com/movie/?p=
  douban: https://movie.douban.com
  btt:
    site: http://btbtt.co/
    page: http://btbtt.co/forum-index-fid-%d-page-%d.htm
    thread: http://btbtt.co/thread-index-fid-%d-tid-%d.htm
  rarbt:
    site: http://www.rarbt.com
    page: http://www.rarbt.com/index.php/index/index/p/%d.html
  bttt:
    site: http://www.bttiantang.org
    page: http://www.bttiantang.org/index-%d.html
  btapple:
    site: http://www.btapple.com
    page: http://www.btapple.com/%s/1-0-0-0-0-%d.html
file:
  download: /tmp/bt/

---
spring:
  profiles: dev
logging:
  level:
    org.springframework:
     web: DEBUG

---
spring:
  profiles: test
# JPA
  jpa:
    show-sql: true
    database: H2
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: create-drop
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
logging:
  level:
    org.springframework:
     web: DEBUG
